### ISSUE TITLE
Restructuring college essays

### ISSUE THREAD

**Issue by jonahweissman** [Tim-Jackins/Tim-Jackins.github.io#3]
Your college essay page has some great info about you, but it's kind of a weird format. I think it would be better if you put that information in bullet points or add it to your resume.

**Comment by Tim-Jackins** [comment]
I turn it into a bio see how it looks?

**Comment by jonahweissman** [comment]
Makes much more sense that way, thanks 👍. Also, side question: is this site aimed primarily at potential employers? If so, the hobbies section feels a little weird.

**Comment by Tim-Jackins** [comment]
Makes sense, I'll remove it

**Comment by jonahweissman** [comment]
Already removed on PR #5

**Comment by Tim-Jackins** [comment]
Nice
