### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by jonahweissman** [Tim-Jackins/Tim-Jackins.github.io#6]
Did you mean to have a Creative Commons license on your website? It just seems a little odd to license your lab report and resume that way.

**Comment by Tim-Jackins** [comment]
I'm switching it to MIT, thanks

**Comment by jonahweissman** [comment]
Not quite what I meant. [CC is a good choice for a website](https://choosealicense.com/non-software/), but I didn't know if you meant to make your resume open-source.
